CREATE DATABASE artdb CHARACTER SET utf8 COLLATE utf8_bin;
GRANT ALL ON artdb.* TO 'USER_HERE'@'localhost' IDENTIFIED BY 'PASSWORD_HERE';
GRANT ALL ON artdb.* TO 'USER_HERE'@'SUBNET_HERE.%' IDENTIFIED BY 'PASSWORD_HERE';
FLUSH PRIVILEGES;
